import os
import json
from google import genai
from github import Github

gh = Github(os.getenv("GITHUB_TOKEN"))
repo = gh.get_repo(os.getenv("GITHUB_REPOSITORY"))


def run_remediation():
    # Generate content using Gemini
    client = genai.Client()
    gemini_response = client.models.generate_content(
        model="gemini-3-pro-preview",
        contents="Provide vulnerability remediation suggestions"
    )
    
    # Get the generated response
    remediation_text = gemini_response.text
    
    # Create a new branch
    branch_name = f"auto_remediation"
    
    # Get the default branch (main or master)
    main_branch = repo.get_branch(repo.default_branch)
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha)

    try:
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=main_branch.commit.sha
        )
    except Exception:
        print("Branch already exists, using existing branch.")

    # 3. Fetch app.py from default branch
    file_path = "app.py"
    file_obj = repo.get_contents(file_path, ref=repo.default_branch)

    # 4. Read file and split into lines
    lines = file_obj.decoded_content.decode().splitlines()

    # 5. Replace ONLY line 25 (index 24)
    lines[24] = remediation_text

    # 6. Reconstruct file content
    updated_content = "\n".join(lines)

    # 7. Commit updated file to new branch
    repo.update_file(
        path=file_path,
        message="AI remediation: update response on line 25",
        content=updated_content,
        sha=repo.get_contents(file_path, ref=branch_name).sha,
        branch=branch_name
    )

    print("New branch commited with AI remediation.")
    # 8. Create a pull request
    create_pull_request()


def create_pull_request():
    pr_title = "[Security] Automated AI Remediation"
    pr_body = (
        "This pull request was automatically generated by an AI remediation agent.\n\n"
        "### Details\n"
        "- Source: Gemini AI\n"
        "- Trigger: Automated remediation workflow\n"
        "- Scope: app.py (line-level fix)\n\n"
        "Please review before merging."
    )

    head_branch = "auto_remediation"
    base_branch = repo.default_branch

    try:
        repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=head_branch,
            base=base_branch
        )
        print("Pull request created successfully.")
    except Exception as e:
        print(f"Pull request creation failed: {e}")

if __name__ == "__main__":
    run_remediation()