on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 51 0 * * *
name: Semgrep

permissions:
  contents: read 
  security-events: write
  actions: read
  checks: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci --sarif > semgrep.sarif
    - name: Upload Semgrep SARIF to Security Tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: semgrep.sarif
        category: semgrep
    - name: Save SARIF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif
        path: semgrep.sarif
